using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPGA.Common
{
	//all non-enums in this partial
	public static partial class Constants
	{
		public static class Defaults
		{
			public static int Speed => 30;
			public static string Size => nameof(Sizes.Medium);
			public static int? Darkvision => null;
			public static int ProficiencyBonus => 2;
		}

		public enum Dice
		{
			D3,
			D4,
			D6,
			D8,
			D10,
			D12,
			D20
		}

		public enum SpecialFeatures
		{
			[Display(Name = "None")] None,
			[Display(Name = "Healing Hands")] HealingHands,
			[Display(Name = "Light Bearer")] LightBearer,
			[Display(Name = "Radiant Soul")] RadiantSoul,
			[Display(Name = "Radiant Consumption")] RadiantConsumption,
			[Display(Name = "Necrotic Shroud")] NecroticShroud,
			[Display(Name = "Dwarven Resilience")] DwarvenResilience,
			[Display(Name = "Dwarven Toughness")] DwarvenToughness,
			[Display(Name = "Dwarven Armor Training")] DwarvenArmorTraining,
			[Display(Name = "Dwarven Combat Training")] DwarvenCombatTraining,
			[Display(Name = "Stonecunning")] Stonecunning,
			[Display(Name = "Duergar Magic")] DuergarMagic,
			[Display(Name = "Sunlight Sensitivity")] SunlightSensitivity,
			[Display(Name = "Damage Resistance")] DragonbornDamageResistance,
			[Display(Name = "Fey Ancestry")] FeyAncestry,
			[Display(Name = "Trance")] Trance,
			[Display(Name = "Bonus Language")] BonusLanguage,
			[Display(Name = "Elf Weapon Training")] ElfWeaponTraining,
			[Display(Name = "Cantrip")] ElfCantrip,
			[Display(Name = "Fleet Of Foot")] FleetOfFoot,
			[Display(Name = "Mask of the Wild")] MaskOfTheWild,
			[Display(Name = "Drow Weapon Training")] DrowWeaponTraining,
			[Display(Name = "Drow Magic")] DrowMagic,
			[Display(Name = "Gnome Cunning")] GnomeCunning,
			[Display(Name = "Natural Illusionist")] NaturalIllusionist,
			[Display(Name = "Speak with Small Beasts")] SpeakWithSmallBeasts,
			[Display(Name = "Artificers Lore")] ArtificersLore,
			[Display(Name = "Tinker")] Tinker,
			[Display(Name = "Svirfneblin Magic")] SvirfneblinMagic,
			[Display(Name = "Stone Camouflage")] StoneCamouflage,
			[Display(Name = "Natural Athlete")] NaturalAthlete,
			[Display(Name = "Stones Endurance")] StonesEndurance,
			[Display(Name = "Powerful Build")] PowerfulBuild,
			[Display(Name = "Mountain Born")] MountainBorn,
			[Display(Name = "Skill Versatility")] SkillVersatility,
			[Display(Name = "Bonus Ability Scores")] HumanAbilityBonus,
			[Display(Name = "Bonus Ability Scores")] HalfelfAbilityBonus,
			[Display(Name = "Menacing")] Menacing,
			[Display(Name = "Relentless Endurance")] RelentlessEndurance,
			[Display(Name = "Savage Attacks")] SavageAttacks,
			[Display(Name = "Lucky")] Lucky,
			[Display(Name = "Brave")] Brave,
			[Display(Name = "Halfling Nimbleness")] HalflingNimbleness,
			[Display(Name = "Naturally Stealthy")] NaturallyStealthy,
			[Display(Name = "Stout Resilience")] StoutResilience,
			[Display(Name = "Firbolg Magic")] FirbolgMagic,
			[Display(Name = "Hidden Step")] HiddenStep,
			[Display(Name = "Speech of Beast and Leaf")] SpeechOfBeastAndLeaf,
			[Display(Name = "Expert Forgery")] ExpertForgery,
			[Display(Name = "Kenku Training")] KenkuTraining,
			[Display(Name = "Mimicry")] Mimicry,
			[Display(Name = "Natural Armor")] LizardfolkNaturalArmor,
			[Display(Name = "Bite Attack")] LizardfolkBiteAttack,
			[Display(Name = "Hold Breath")] HoldBreath,
			[Display(Name = "Cunning Artisan")] CunningArtisan,
			[Display(Name = "Hunter's Lore")] HuntersLore,
			[Display(Name = "Hungry Jaws")] HungryJaws,
			[Display(Name = "Feline Agility")] FelineAgility,
			[Display(Name = "Cat's Claws")] CatsClaws,
			[Display(Name = "Cats Talent")] CatsTalent,
			[Display(Name = "Hellish Resistance")] HellishResistance,
			[Display(Name = "Infernal Legacy")] InfernalLegacy,
			[Display(Name = "Amphibious")] Amphibious,
			[Display(Name = "Control Air and Water")] ControlAirAndWater,
			[Display(Name = "Emissary of the Sea")] EmissaryOfTheSea,
			[Display(Name = "Guardians of the Depths")] GuardiansOfTheDepths,
			[Display(Name = "Rage")] BarbarianRage,
			[Display(Name = "Unarmored Defense")] BarbarianUnarmoredDefense,
			[Display(Name = "Cantrips")] ClericCantrips,
			[Display(Name = "Spellcasting")] WisdomCasting,
			[Display(Name = "Fighting Style")] FightingStyle,
			[Display(Name = "Second Wind")] SecondWind,
			[Display(Name = "Unarmored Defense")] MonkUnarmoredDefense,
			[Display(Name = "Martial Arts")] MartialArts,
			[Display(Name = "Divine Sense")] DivineSense,
			[Display(Name = "Lay On Hands")] LayOnHands,
			[Display(Name = "Favored Enemy")] FavoredEnemy,
			[Display(Name = "Natural Explorer")] NaturalExplorer,
			[Display(Name = "Sneak Attack")] SneakAttack,
			[Display(Name = "Expertise")] Expertise,
			[Display(Name = "Thieves' Cant")] ThievesCant,
			[Display(Name = "Charisma Casting")] CharismaCasting,
			[Display(Name = "Sorcerous Origin")] SorcerousOrigin,
			[Display(Name = "Bardic Inspiration")] BardicInspiration,
			[Display(Name = "Otherworldly Patron")] OtherworldlyPatron,
			[Display(Name = "Pact Magic")] PactMagic,
			[Display(Name = "Intelligence Casting")] IntelligenceCasting,
			[Display(Name = "Arcane Recovery")] ArcaneRecovery,

		}

		public static Dictionary<SpecialFeatures, string> SpecialFeaturesDescriptions = new Dictionary<SpecialFeatures, string>
		{
			{ SpecialFeatures.HealingHands, "As an action, you can touch a creature and heal a number of hit points equal to your level, once per long rest." },
			{ SpecialFeatures.LightBearer, "You know the light cantrip. Charisma is your spellcasting ability for it." },
			{ SpecialFeatures.RadiantSoul, "Starting at 3rd level, you can unleash the divine energy as an action. When you do so, your eyes glimmer and two luminous, incorporeal wings emerge from your back and you gain a flying speed of 30 feet. The transformation lasts for 1 min, and once on each of your turns you can deal extra radiant damage equal to your level, whenever you damage a creature with an attack or spell. You can cancel Radiant Soul with a bonus action, and cannot use it again until you take a long rest." },
			{ SpecialFeatures.RadiantConsumption, "Starting at 3rd level, you can use your action to unleash the divine energy within yourself, causing a searing light to radiate from you, pour out of your eyes and mouth, and threaten to char you. Your transformation lasts for 1 minute or until you end it as a bonus action. During it, you shed bright light in a 10-foot radius and dim light for an additional 10 feet, and at the end of each of your turns, you and each creature within 10 feet of you take radiant damage equal to half your level (rounded up). In addition, once on each of your turns, you can deal extra radiant damage to one target when you deal damage to it with an attack or a spell. The extra radiant damage equals your level. Once you use this trait, you can't use it again until you finish a long rest." },
			{ SpecialFeatures.NecroticShroud, "Starting at 3rd level, you can unleash your divine energy as an action, causing your eyes to turn into pools of darkness and two skeletal, ghostly, flightless wings sprout from your back. The instant you transform, all other creatures within 10 feet that can see you become frightened until the end of your next turn if they fail a Charisma saving throw (DC 8 + your prof bonus + Charisma modifier). The transformation lasts for 1 minute, and once on each of your turns you can deal extra necrotic damage equal to your level, whenever you damage a creature with an attack or spell. You can cancel Necrotic Shroud with a bonus action, and cannot use it again until you take a long rest." },
			{ SpecialFeatures.DragonbornDamageResistance, "You have Resistance to the damage type associated with your draconic ancestry." },
			{ SpecialFeatures.DwarvenResilience, "Advantage on saves vs poison, and resistance to poison damage." },
			{ SpecialFeatures.DwarvenCombatTraining, "Proficiency with the battleaxe, handaxe, light hammer, and warhammer." },
			{ SpecialFeatures.Stonecunning, "When determining the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check." },
			{ SpecialFeatures.DuergarMagic, "At 3rd level, you can cast the Enlarge spell on yourself once per long rest. At 5th level, you can cast Invisibility once per long rest. You need no material components and you can't cast either of them in direct sunlight, though sunlight has no effect once they're cast." },
			{ SpecialFeatures.SunlightSensitivity, "Disadvantage on attack rolls and Perception (sight) checks when you or your target is in direct sunlight." },
			{ SpecialFeatures.FeyAncestry, "Advantage on saves against magical charms, and you can't be put to sleep with magic." },
			{ SpecialFeatures.Trance, "Can meditate for 4 hours a day instead of sleeping for 8 hours." },
			{ SpecialFeatures.BonusLanguage, "One extra language of your choice." },
			{ SpecialFeatures.ElfWeaponTraining, "Proficiency in longsword, shortsword, shortbow, and longbow."},
			{ SpecialFeatures.ElfCantrip, "Gain one Wizard cantrip of your choice using Intelligence for it." },
			{ SpecialFeatures.FleetOfFoot, "Speed 35 feet" },
			{ SpecialFeatures.MaskOfTheWild, "You can try to hide when lightly obscured by foliage, heavy rain, falling snow, mist, and other natural phenomena." },
			{ SpecialFeatures.DrowWeaponTraining, "Proficiency in rapiers, shortswords, and hand crossbows." },
			{ SpecialFeatures.DrowMagic, "At 1st level, you gain the Dancing Lights cantrip, at 3rd level you can cast Faerie Fire once per long rest, and at 5th level you can cast Darkness once per long rest. Charisma is your spellcasting ability." },
			{ SpecialFeatures.DwarvenArmorTraining, "Proficiency with light and medium armor." },
			{ SpecialFeatures.DwarvenToughness, "Your hit point maximum increases by 1, and it increases by 1 every time you gain a level." },
			{ SpecialFeatures.GnomeCunning, "Advantage on all Intelligence, Wisdom, and Charisma saving throws against magic." },
			{ SpecialFeatures.NaturalIllusionist, "You know the Minor Illusion cantrip. Intelligence is your spellcasting ability for it." },
			{ SpecialFeatures.SpeakWithSmallBeasts, "Through sounds and gestures, you can communicate simple ideas with small or smaller beasts. Forest gnomes love animals and often keep squirrels, badgers, rabbits, moles, woodpeckers, and other creatures as beloved pets." },
			{ SpecialFeatures.ArtificersLore, "Whenever you make an Intelligence (History) check related to magic items, alchemical objects, or technological devices, you can add twice your proficiency bonus." },
			{ SpecialFeatures.Tinker, "Proficiency with Tinker's Tools. You can spend 1 hour and 10 gp worth of materials to construct a Tiny clockwork device (AC 5, 1 hp). The device ceases to function after 24 hours (unless you spend 1 hour repairing it to keep the device functioning), or when you use your action to dismantle it; at that time, you can reclaim the materials used to create it. " },
			{ SpecialFeatures.StoneCamouflage, "Advantage on Stealth checks to hide in rocky terrain." },
			{ SpecialFeatures.SvirfneblinMagic, "Although they don't begin with it, Deep Gnomes gain access to the Svirfneblin Magic feat which allows them to cast Nondetection on yourself at will, and once per long rest you can cast Blindness/Deafness, Blur, and Disguise Self. Intelligence is your spellcasting ability for these spells." },
			{ SpecialFeatures.NaturalAthlete, " Proficiency in the Athletics skill." },
			{ SpecialFeatures.StonesEndurance, "Once per short or long rest, you can use your reaction to reduce damage taken by 1d12 + your Constitution bonus." },
			{ SpecialFeatures.PowerfulBuild, "You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift." },
			{ SpecialFeatures.MountainBorn, "You're acclimated to extremely high altitude and naturally adapted to cold climates as described in chapter 5 of the Dungeon Master's Guide. In short you will not accrue levels of exhaustion caused by cold climates." },
			{ SpecialFeatures.SkillVersatility, "Proficiency in two skills of your choice." },
			{ SpecialFeatures.HumanAbilityBonus, "+1 to all Ability Scores" },
			{ SpecialFeatures.HalfelfAbilityBonus, "Any two (not Charisma) ability scores +1." },
			{ SpecialFeatures.Menacing, "Proficiency in the Intimidation skill." },
			{ SpecialFeatures.RelentlessEndurance, "Once per long rest, when you are reduced to 0 hit points but not killed outright, you can drop to 1 hit point instead." },
			{ SpecialFeatures.SavageAttacks, "When you score a critical hit with a melee weapon attack, you can roll one of the weapon's damage dice one additional time and add it to the extra damage of the critical hit." },
			{ SpecialFeatures.Lucky, "When you roll a 1 on an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll." },
			{ SpecialFeatures.Brave, "You have advantage on saving throws against being frightened." },
			{ SpecialFeatures.HalflingNimbleness, "You can move through the space of any creature that is of a size larger than yours." },
			{ SpecialFeatures.NaturallyStealthy, "You can attempt to hide even when you are obscured only by a creature that is at least one size larger than you." },
			{ SpecialFeatures.StoutResilience, "You have advantage on saving throws against poison, and you have resistance against poison damage." },
			{ SpecialFeatures.FirbolgMagic, "Once per short or long rest you can cast both the Detect Magic and Disguise Self spells using Wisdom as your spellcasting ability. This version of Disguise Self lets you appear up to 3 feet shorter, thus allowing you to blend in with humans and elves." },
			{ SpecialFeatures.HiddenStep, "Once per short or long rest, you can magically turn Invisible until the start of your next turn as a bonus action. The ability ends early if you attack, deal any damage, or force anyone to make a saving throw." },
			{ SpecialFeatures.SpeechOfBeastAndLeaf, "You can communicate with beasts and plants. You also have advantage on Charisma checks to influence them. These creatures can understand the meaning of your words, even though you cannot understand them in return." },
			{ SpecialFeatures.ExpertForgery, "You can duplicate other creatures' handwriting and craftwork. You have advantage on all checks made to produce forgeries or duplicates of existing objects." },
			{ SpecialFeatures.KenkuTraining, "You are proficient in your choice of two of the following skills: Acrobatics, Deception, Stealth, and Sleight of Hand." },
			{ SpecialFeatures.Mimicry, "You can mimic sounds you have heard, including voices. A creature that hears the sounds you make can tell they are imitations with a successful Wisdom (Insight) check opposed by your Charisma (Deception) check." },
			{ SpecialFeatures.LizardfolkNaturalArmor, "You have tough, scaly skin. When you aren't wearing armor, your AC is 13 + your Dexterity modifier. You can use your natural armor to determine your AC if the armor you wear would leave you with a lower AC. A shield's benefits apply as normal while you use your natural armor." },
			{ SpecialFeatures.LizardfolkBiteAttack, "Your fanged maw is a natural weapon, which you can use to make unarmed strikes. If you hit with it, you deal piercing damage equal to 1d6 + your Strength modifier, instead of the bludgeoning damage normal for an unarmed strike." },
			{ SpecialFeatures.HoldBreath, "You can hold your breath for up to 15 minutes." },
			{ SpecialFeatures.CunningArtisan, "As part of a short rest, you can harvest bone and hide from a slain beast, construct, dragon, monstrosity, or plant creature of size Small or larger to create one of the following items: a shield, a club, a javelin, or 1d4 darts or blowgun needles. To use this trait, you need a blade, such as a dagger, or appropriate artisan's tools, such as leatherworker's tools." },
			{ SpecialFeatures.HuntersLore, "You gain proficiency with two of the following skills of your choice: Animal Handling, Nature, Perception, Stealth, and Survival." },
			{ SpecialFeatures.HungryJaws, "In battle, you can throw yourself into a vicious feeding frenzy. As a bonus action, you can make a special attack with your bite. If the attack hits, it deals its normal damage, and you gain temporary hit points (minimum of 1) equal to your Constitution modifier, and you can't use this trait again until you finish a short or long rest." },
			{ SpecialFeatures.FelineAgility, "Your reflexes and agility allow you to move with a burst of speed. When you move on your turn in combat, you can double your speed until the end of your turn. Once you use this trait, you can't use it again until you move 0 feet on one of your turns." },
			{ SpecialFeatures.CatsClaws, "Because of your claws, you have a climbing speed of 20 feet. In addition, your claws are natural weapons, which you can use to make unarmed strikes. If you hit with them, you deal slashing damage equal to 1d4 + your Strength modifier, instead of the bludgeoning damage normal for an unarmed strike." },
			{ SpecialFeatures.CatsTalent, "You gain proficiency in the Perception and Stealth skills." },
			{ SpecialFeatures.HellishResistance, "Resistance to fire damage." },
			{ SpecialFeatures.InfernalLegacy, "You know the Thaumaturgy cantrip. Once you reach 3rd level, you can cast the Hellish Rebuke spell as a 2nd-level spell, once per long rest. Once you reach 5th level, you can also cast the Darkness spell, once per long rest. Charisma is your spellcasting ability for these spells." },
			{ SpecialFeatures.Amphibious, "You can breathe air and water." },
			{ SpecialFeatures.ControlAirAndWater, "A child of the sea, you can call on the magic of elemental air and water. You can cast Fog Cloud with this trait. Starting at 3rd level, you can cast Gust of Wind with it, and starting at 5th level, you can also cast Wall of Water with it. Once you cast a spell with this trait, you can't do so again until you finish a long rest. Charisma is your spellcasting ability for these spells." },
			{ SpecialFeatures.EmissaryOfTheSea, "Aquatic beasts have an extraordinary affinity with your people. You can communicate simple ideas with beasts that can breathe water. They can understand the meaning of your words, though you have no special ability to understand them in return." },
			{ SpecialFeatures.GuardiansOfTheDepths, "Adapted to even the most extreme ocean depths, you have resistance to cold damage, and you ignore any of the drawbacks caused by a deep, underwater environment." },
			{ SpecialFeatures.BarbarianRage, "In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action." },
			{ SpecialFeatures.BarbarianUnarmoredDefense, "While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit." },
			{ SpecialFeatures.ClericCantrips, "At 1st level, you know three Cantrips of your choice from the cleric spell list. You learn additional Cleric Cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Cleric table." },
			{ SpecialFeatures.WisdomCasting, "Wisdom is your spellcasting ability for your Spells. The power of your Spells comes from your devotion to your deity. You use your Wisdom whenever a spell refers to your spellcasting ability. In addition, you use your Wisdom modifier when Setting the saving throw DC for a spell you cast and when Making an Attack roll with one." },
			{ SpecialFeatures.SecondWind, "At first level, you have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use a bonus action to regain hit points equal to 1d10 + your fighter level. Once you use this feature, you must finish a short or long rest before you can use it again." },
			{ SpecialFeatures.FightingStyle, "At first level, you adopt a particular style of fighting as your specialty." },
			{ SpecialFeatures.MonkUnarmoredDefense, "At 1st level, if you wear no armor nor shield your AC is 10+DEX mod+WIS mod, this is lost and replaced by the normal armor AC and shield bonus if you equip armor or a shield." },
			{ SpecialFeatures.MartialArts, "You have mastery over unarmed combat and certain types of weapons called Monk weapons, which are short swords or any simple melee weapon that does not have the Heavy or Two-Handed property." },
			{ SpecialFeatures.DivineSense, "The presence of strong evil registers on your senses like a noxious odor, and powerful good rings like heavenly music in your ears. As an action, you can open your awareness to detect such forces. Until the end of your next turn, you know the location of any celestial, fiend, or undead within 60 feet of you that is not behind total cover." },
			{ SpecialFeatures.LayOnHands, "Your blessed touch can heal wounds. You have a pool of healing power that replenishes when you take a long rest. With that pool, you can restore a total number of hit points equal to your paladin level x 5." },
			{ SpecialFeatures.FavoredEnemy, "You have advantage on Wisdom (Survival) checks to track your favored enemies, as well as on Intelligence checks to recall information about them. When you gain this feature, you also learn one language of your choice that is spoken by your favored enemies, if they speak one at all." },
			{ SpecialFeatures.NaturalExplorer, "Choose one type of favored terrain: arctic, coast, desert, forest, grassland, mountain, swamp, or the Underdark. When you make an Intelligence or Wisdom check related to your favored terrain, your proficiency bonus is doubled." },
			{ SpecialFeatures.SneakAttack, " Once per turn, you can deal extra 1d6 damage to one creature you hit with an attack if you have advantage on the attack roll." },
			{ SpecialFeatures.Expertise, "At 1st level, choose two of your skill proficiencies, or one of your skill proficiencies and your proficiency with thieves' tools. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies." },
			{ SpecialFeatures.ThievesCant, "During your rogue training you learned thieves’ cant, a secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation." },
			{ SpecialFeatures.CharismaCasting, "Charisma is your spellcasting ability for your spells, since the power of your magic relies on your ability to project your will into the world." },
			{ SpecialFeatures.SorcerousOrigin, "Choose a sorcerous origin, which describes the source of your innate magical power: Draconic Bloodline, Wild Magic, Divine Soul, Shadow Magic, Storm Sorcery, Phoenix Sorcery, Sea Sorcery, Stone Sorcery, or Pyromancer." },
			{ SpecialFeatures.BardicInspiration, "You can inspire others through stirring words or music. To do so, you use a bonus action on your turn to choose one creature other than yourself within 60 feet of you who can hear you. That creature gains one Bardic Inspiration die, a d6." },
			{ SpecialFeatures.OtherworldlyPatron, "At 1st level, you have struck a bargain with an otherworldly being of your choice: the Archfey, the Celestial, the Fiend, the Great Old One, the Hexblade, the Raven Queen, the Seeker, or the Undying, each of which is detailed at the end of the class description. Your choice grants you special features." },
			{ SpecialFeatures.PactMagic, "Your arcane research and the magic bestowed on you by your patron have given you facility with spells from the Warlock Spell List." },
			{ SpecialFeatures.IntelligenceCasting, "Intelligence is your spellcasting ability for your spells, since you learn your spells through dedicated study and memorization. You use your Intelligence whenever a spell refers to your spellcasting ability." },
			{ SpecialFeatures.ArcaneRecovery, "You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher." },
			{ SpecialFeatures.None, "Template" },

		};
	}
}